easy_admin:
  formats:
    datetime:     'd/m/Y'
  entities:
    Author:
      class: App\Entity\Author
    Book:
      class: App\Entity\Book
      list:
        fields:
          - title
          - createdAt
          - purchaseDate
          - readingDate
          - { property: 'yearOfPublication', format: 'Y' }
          - format
          - { property: 'isShortStory', type: 'boolean' }
      form:
        fields:
          - title
          - authors
          - purchaseDate
          - readingDate
          - yearOfPublication
          - { property: 'format', type: 'choice', type_options: {choices: {'Paper book': 'paper-book', 'Ebook': 'ebook', 'Audiobook': 'audiobook'}}}
          - isShortStory
