version: '2.3'
services:
  proxy:
    image: nginx:1.15
    ports:
      - "8080:80"
    volumes:
      - .:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql:rw
  php:
    image: php:7.2-fpm-stretch
    volumes:
      - .:/code
